language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.4
  - 5.5
  - 5.6
  - nightly
  - hhvm

matrix:
  include:
    - php: 5.4
      env: COMPOSER_FLAGS="--prefer-lowest"
  allow_failures:
    - php: nightly
    - php: hhvm-nightly
  fast_finish: true

before_script:
  - composer self-update
  - composer config -g github-oauth.github.com $GITHUB_OAUTH_TOKEN
  - composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script:
  - vendor/bin/phpspec run
  - vendor/bin/phpunit tests
