language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.4
  - 5.5
  - 5.6
  - nightly
  - hhvm

matrix:
    allow_failures:
        - php: nightly
        - php: hhvm-nightly
    fast_finish: true

before_script:
    - composer self-update

install:
  - composer install --dev

script:
  - vendor/bin/phpspec run
  - vendor/bin/phpunit tests
